baseurl = "/"
languageCode = "en-us"
title = "MakerHut"
theme = "hugo-creative-theme"
googleAnalytics = "UA-96769525-1"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "MakerHut - Zambia's very own maker community"
	description = "Makerhut is a creative community in Zambia that explores projects and technology in the fields of Electronics, Arts and Industrial Design."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "MakerHut"

		[params.navigation.links]
			about     = "About"
			services  = "Ethos"
			portfolio = "Get involved"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Zambia's very own maker movement"
		subtitle   = "A STEAM (Science, Technology, Engineering, Arts and Mathematics) powered initiative for curious minds that want to use technology to build an awesome future."
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "About"
		description = "MakerHut is a creative community of makers in Zambia that explores projects and technology in the fields of electronics, crafts and industrial design. Our future involves a radically transformed STEAM education culture in Southern Africa and a generation of youth building an amazing future for our continent."
		buttonText  = "Read about us"


	# Service section
	[params.services]
		headline = "What we believe in"

        [[params.services.list]]
            icon = "fa-hand-spock-o"
            title = "Hands on Learning"
            description = "We realise the value in hands-on learning and that everyone has the capacity to build novel ideas regardless of age and background. We'll show you that the best (and most fun) way of learning is by doing"

        [[params.services.list]]
			icon = "fa-space-shuttle"
			title = "Modern Tools"
			description = "DIY tools and technology have become increasingly affordable and accessible. Dive into hobby electronics with us using everything from Arduinos and Raspberry Pis to Spark Cores and litteBits."

		[[params.services.list]]
            icon = "fa-paint-brush"
            title = "Creative Expression"
            description = "Creative thinking has been a major key to solving many of humanities problems and advancing civilisation. Crafts, art and design are integrated in our program to help develop critical thinking."

        [[params.services.list]]
            icon = "fa-book"
            title = "Maker Education"
            description = "As an official partner of MakerEd through the Maker Corps program, we are working on a curriculum to bring sustainable maker education to primary and secondary students."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Subscribe to the MakerHut newsletter for updates on new programs and events"

		[params.aside.button]
			text = "Subscribe"
			link = "http://eepurl.com/cJgipD"

	# Contact section
	[params.contact]
		headline = "Contact us"
		description = "If you'd like to hear from us, we'd like to hear from you"
		phone = "097-211-1456"
		email = "contact@makerhut.org"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
